// Generated by Wrangler by running `wrangler types`

interface Env {
	TELEGRAM_BOT_KEY: string;
	BETTER_AUTH_SECRET: string;
	SMTP_KEY: string;
	SMTP_SERVER_HOST: string;
	SMTP_SERVER_USER: string;
	EMAIL_FROM: string;
	SUPER_GROUP_CHAT_ID: string;
	DATABASE: D1Database;
}
